name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Access via ssh  
        uses: appleboy/ssh-action@v1.0.0
          with: 
            host: ${{ secrets.SSH_HOST }}  
            username: root  
            key: ${{ secrets.SSH_KEY }}  



      - name: Deploy to Server
        run: |
              ssh -T -o StrictHostKeyChecking=no root@168.119.254.41 << 'EOF'
              cd ~/abdullah/docker-01
              docker pull busybox
              docker container run -d --name my-container -p 80:5000 busybox
              EOF
