name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        



      - name: Deploy to Server
        run: |
              ssh -T -o StrictHostKeyChecking=no root@168.119.254.41 << 'EOF'
              cd ~/abdullah/Test
              git pull origin main
              npm install
              nohup npm start &> output.log &
              EOF
