name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}



      - name: Deploy to Server
        run: |
              ssh -T -o StrictHostKeyChecking=no root@168.119.254.41 << 'EOF'
              cd ~/abdullah/docker-01
              docker pull busybox
              docker container run -d --name my-container -p 80:5000 busybox
              EOF
